<template>
  <div class="container mt-4">
    <div class="row">
      <div class="col-12">
        <h2
          class="font-weight-bold"
          style="font-family:'Montserrat', sans-serif; color:#292929; text-align:center"
        >Paket Hosting Singapura yang Tepat</h2>
        <h2
          class="h3 font-weight-light"
          style="font-family:'Montserrat', sans-serif; color:#292929; text-align:center"
        >Diskon 40% + Domain dan SSL Gratis untuk Anda</h2>
      </div>
      <div class="col-3 mt-5">
        <div class="card" style="width: 18rem;">
          <div class="content-card card-body text-center">
            <h3 class="card-title font-weight-bold">Bayi</h3>
            <h5 class="card-title font-weight-light">
              <s>Rp. 19.900</s>
            </h5>
            <h3 class="card-title font-weight-bold">Rp. 14.900/bln</h3>
            <p class="card-text">
              <b>938</b> Pengguna Terdaftar
            </p>
            <span>0.5x RESOURCES POWER</span>
            <br />
            <span>
              <b>500 MB</b> Disk Space
            </span>
            <br />
            <span>
              <b>Unlimited Bandwith</b>
            </span>
            <br />
            <span>
              <b>Unlimited Database</b>
            </span>
            <br />
            <span>
              <b>1</b> Domain
            </span>
            <br />
            <span>
              <b>Instant</b> Backup
            </span>
            <br />
            <span>
              <b>Unlimited SSL</b> Gratis Selamanya
            </span>
            <br />
            <br />
            <a href="#" class="button-pilih btn btn-outline-dark">Pilih Sekarang</a>
          </div>
        </div>
      </div>
      <div class="col-3 mt-5">
        <div class="card" style="width: 18rem;">
          <div class="content-card card-body text-center">
            <h3 class="card-title font-weight-bold">Pelajar</h3>
            <h5 class="card-title font-weight-light">
              <s>Rp. 46.900</s>
            </h5>
            <h3 class="card-title font-weight-bold">Rp. 23.450/bln</h3>
            <p class="card-text">
              <b>4.168</b> Pengguna Terdaftar
            </p>
            <span>1x RESOURCES POWER</span>
            <br />
            <span>
              <b>Unlimited</b> Disk Space
            </span>
            <br />
            <span>
              <b>Unlimited Bandwith</b>
            </span>
            <br />
            <span>
              <b>Unlimited</b> POP3 Email
            </span>
            <br />
            <span>
              <b>Unlimited</b> Database
            </span>
            <br />
            <span>
              <b>10</b> Addon Domains
            </span>
            <br />
            <span>
              <b>Instant</b> Backup
            </span>
            <br />
            <span>
              <b>Domain Gratis</b> Selamanya
            </span>
            <br />
            <span>
              <b>Unlimited SSL</b> Selamanya
            </span>
            <br />
            <br />
            <a href="#" class="button-pilih btn btn-outline-dark">Pilih Sekarang</a>
          </div>
        </div>
      </div>

      <div class="col-3 mt-5">
        <div class="card" style="width: 18rem;">
          <div class="content-card card-body text-center">
            <h3 class="card-title font-weight-bold">Personal</h3>
            <h5 class="card-title font-weight-light">
              <s>Rp. 58.900</s>
            </h5>
            <h3 class="card-title font-weight-bold">Rp. 38.900/bln</h3>
            <p class="card-text">
              <b>10.017</b> Pengguna Terdaftar
            </p>
            <span>2x RESOURCES POWER</span>
            <br />
            <span>
              <b>Unlimited</b> Disk Space
            </span>
            <br />
            <span>
              <b>Unlimited Bandwith</b>
            </span>
            <br />
            <span>
              <b>Unlimited</b> POP3 Email
            </span>
            <br />
            <span>
              <b>Unlimited</b> Database
            </span>
            <br />
            <span>
              <b>Unlmited</b> Addon Domains
            </span>
            <br />
            <span>
              <b>Instant</b> Backup
            </span>
            <br />
            <span>
              <b>Domain Gratis</b> Selamanya
            </span>
            <br />
            <span>
              <b>Unlimited SSL</b> Selamanya
            </span>
            <br />
            <span>
              <b>Private Name</b> Server
            </span>
            <br />
            <span>
              <b>Spam Assasin</b> Mail Protection
            </span>
            <br />
            <br />
            <a href="#" class="button-pilih btn btn-primary">Pilih Sekarang</a>
          </div>
        </div>
      </div>

      <div class="col-3 mt-5">
        <div class="card" style="width: 18rem;">
          <div class="content-card card-body text-center">
            <h3 class="card-title font-weight-bold">Bisnis</h3>
            <h5 class="card-title font-weight-light">
              <s>Rp. 109.900</s>
            </h5>
            <h3 class="card-title font-weight-bold">Rp. 65.900/bln</h3>
            <p class="card-text">
              <b>3.552</b> Pengguna Terdaftar
            </p>
            <span>3x RESOURCES POWER</span>
            <br />
            <span>
              <b>Unlimited</b> Disk Space
            </span>
            <br />
            <span>
              <b>Unlimited Bandwith</b>
            </span>
            <br />
            <span>
              <b>Unlimited</b> POP3 Email
            </span>
            <br />
            <span>
              <b>Unlimited</b> Database
            </span>
            <br />
            <span>
              <b>Unlmited</b> Addon Domains
            </span>
            <br />
            <span>
              <b>Magic Auto</b> Backup & Restore
            </span>
            <br />
            <span>
              <b>Domain Gratis</b> Selamanya
            </span>
            <br />
            <span>
              <b>Unlimited SSL</b> Selamanya
            </span>
            <br />
            <span>
              <b>Private Name</b> Server
            </span>
            <br />
            <span>
              <b>Prioritas Layanan</b> Support
            </span>
            <br />
            <span>
              <b>SpamExpert Pro Mail</b> Protection
            </span>
            <br />
            <br />
            <a href="#" class="button-pilih btn btn-outline-dark">Diskon 40%</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style>
@import url("https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800&family=Roboto&display=swap");

span {
  font-family: "Roboto", sans-serif;
}
</style>